
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileServerService", targetNamespace = "http://ftp/", wsdlLocation = "http://localhost:8080/FileServer?wsdl")
public class FileServerService
    extends Service
{

    private final static URL FILESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESERVERSERVICE_EXCEPTION;
    private final static QName FILESERVERSERVICE_QNAME = new QName("http://ftp/", "FileServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/FileServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESERVERSERVICE_WSDL_LOCATION = url;
        FILESERVERSERVICE_EXCEPTION = e;
    }

    public FileServerService() {
        super(__getWsdlLocation(), FILESERVERSERVICE_QNAME);
    }

    public FileServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESERVERSERVICE_QNAME, features);
    }

    public FileServerService(URL wsdlLocation) {
        super(wsdlLocation, FILESERVERSERVICE_QNAME);
    }

    public FileServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESERVERSERVICE_QNAME, features);
    }

    public FileServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileServer
     */
    @WebEndpoint(name = "FileServerPort")
    public FileServer getFileServerPort() {
        return super.getPort(new QName("http://ftp/", "FileServerPort"), FileServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileServer
     */
    @WebEndpoint(name = "FileServerPort")
    public FileServer getFileServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ftp/", "FileServerPort"), FileServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESERVERSERVICE_EXCEPTION!= null) {
            throw FILESERVERSERVICE_EXCEPTION;
        }
        return FILESERVERSERVICE_WSDL_LOCATION;
    }

}
